# syntax=docker/dockerfile:1
FROM
Learn more about the "FROM" Dockerfile command.
 python:3
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/
