version: "3.3"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=indigo
      - POSTGRES_USER=indigo
      - POSTGRES_PASSWORD=indigo
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:5500
    volumes:
      - .:/code
    ports:
      - "5500:5500"
    depends_on:
      - db
