version: "3.3"
   
services:
  indigo_db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=indigo
      - POSTGRES_USER=indigo
      - POSTGRES_PASSWORD=indigo
  indigo_web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8100
    volumes:
      - .:/code
    ports:
      - "8100:8100"
    depends_on:
      - indigo_db
